import Navbar from "../components/Navbar"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
/** Lo que contiene esto siempre se va a mostrar */
export default function RootLayout({ children }) { /** Aca se le pasa los parametros hijos a la funcion que son las paginas que va a mostrar ademas se pueden añadir mas cosas */
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
